name: 'Deploy markdown files to Carnap'
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: carnap/actions@v1
        with:
          apiKey: '${{ secrets.CARNAP_API_KEY }}'
          # make any newly created documents private
          defaultVisibility: 'LinkOnly'
          # files to include in the upload (important: this must be quoted)
          includeFiles: '["*.pandoc", "img/*.svg"]'
          instanceUrl: 'https://carnap.philosophy.ubc.ca'
